// <auto-generated />
using System;
using ClassNovaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassNovaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531083132_AddBatchTimingAndBranchMapUrl")]
    partial class AddBatchTimingAndBranchMapUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassNovaApi.Models.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_academic_years");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_academic_years_tenant_id");

                    b.ToTable("academic_years", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_year_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_batches");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_batches_academic_year_id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_batches_branch_id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_batches_class_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_batches_tenant_id");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.BatchSubjectTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_batch_subject_teachers");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_batch_subject_teachers_batch_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_batch_subject_teachers_subject_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_batch_subject_teachers_teacher_id");

                    b.HasIndex("TenantId", "BatchId", "SubjectId", "TeacherId")
                        .IsUnique()
                        .HasDatabaseName("ix_batch_subject_teachers_tenant_id_batch_id_subject_id_teache");

                    b.ToTable("batch_subject_teachers", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MapUrl")
                        .HasColumnType("text")
                        .HasColumnName("map_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_branches_tenant_id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_year_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_classes_academic_year_id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_classes_branch_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_classes_tenant_id");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("RoomNo")
                        .HasColumnType("text")
                        .HasColumnName("room_no");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_class_schedules");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_class_schedules_batch_id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_class_schedules_branch_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_class_schedules_subject_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_class_schedules_teacher_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_class_schedules_tenant_id");

                    b.ToTable("class_schedules", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_year_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exam_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_exams_academic_year_id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_exams_batch_id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_exams_branch_id");

                    b.HasIndex("TenantId", "BatchId", "Status")
                        .HasDatabaseName("ix_exams_tenant_id_batch_id_status");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.ExamSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("integer")
                        .HasColumnName("max_marks");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_subjects");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_subjects_exam_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_exam_subjects_subject_id");

                    b.HasIndex("TenantId", "ExamId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_subjects_tenant_id_exam_id_subject_id");

                    b.ToTable("exam_subjects", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.FeePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short?>("DueDay")
                        .HasColumnType("smallint")
                        .HasColumnName("due_day");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fee_plans");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_fee_plans_batch_id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_fee_plans_branch_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_fee_plans_tenant_id");

                    b.ToTable("fee_plans", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Mark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExamSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_subject_id");

                    b.Property<decimal>("MarksObtained")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("marks_obtained");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_marks");

                    b.HasIndex("ExamSubjectId")
                        .HasDatabaseName("ix_marks_exam_subject_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_marks_student_id");

                    b.HasIndex("TenantId", "StudentId")
                        .HasDatabaseName("ix_marks_tenant_id_student_id");

                    b.HasIndex("TenantId", "ExamSubjectId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_marks_tenant_id_exam_subject_id_student_id");

                    b.ToTable("marks", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.PasswordResetOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("OtpSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("otp_salt");

                    b.Property<int>("SendCount")
                        .HasColumnType("integer")
                        .HasColumnName("send_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_otps");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_password_reset_otps_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_otps_user_id");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_otps_email_tenant_id");

                    b.ToTable("password_reset_otps", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FeePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_plan_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text")
                        .HasColumnName("reference_no");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("FeePlanId")
                        .HasDatabaseName("ix_payments_fee_plan_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_payments_student_id");

                    b.HasIndex("TenantId", "StudentId", "PaymentDate")
                        .HasDatabaseName("ix_payments_tenant_id_student_id_payment_date");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.PendingRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("OtpSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("otp_salt");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<int>("SendCount")
                        .HasColumnType("integer")
                        .HasColumnName("send_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pending_registrations");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_pending_registrations_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_pending_registrations_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_pending_registrations_tenant_id");

                    b.ToTable("pending_registrations", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AdmissionNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admission_no");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guardian_name");

                    b.Property<string>("GuardianPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guardian_phone");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_students_branch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_students_user_id");

                    b.HasIndex("TenantId", "AdmissionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_students_tenant_id_admission_no");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.StudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("EnrolledOn")
                        .HasColumnType("date")
                        .HasColumnName("enrolled_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_student_enrollments");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_student_enrollments_batch_id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_student_enrollments_class_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_enrollments_student_id");

                    b.HasIndex("TenantId", "StudentId", "IsActive")
                        .HasDatabaseName("ix_student_enrollments_tenant_id_student_id_is_active");

                    b.ToTable("student_enrollments", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_tenant_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Qualification")
                        .HasColumnType("text")
                        .HasColumnName("qualification");

                    b.Property<string>("SalaryType")
                        .HasColumnType("text")
                        .HasColumnName("salary_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_teachers_branch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_teachers_user_id");

                    b.HasIndex("TenantId", "EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_tenant_id_employee_code");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text")
                        .HasColumnName("custom_domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_type");

                    b.Property<string>("PlanCode")
                        .HasColumnType("text")
                        .HasColumnName("plan_code");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_contact_email");

                    b.Property<string>("PrimaryContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_contact_name");

                    b.Property<string>("PrimaryContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_contact_phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.TenantFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_key");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_features");

                    b.HasIndex("TenantId", "FeatureKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_features_tenant_id_feature_key");

                    b.ToTable("tenant_features", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.TenantSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicLabelBatch")
                        .HasColumnType("text")
                        .HasColumnName("academic_label_batch");

                    b.Property<string>("AcademicLabelClass")
                        .HasColumnType("text")
                        .HasColumnName("academic_label_class");

                    b.Property<string>("AcademicLabelSection")
                        .HasColumnType("text")
                        .HasColumnName("academic_label_section");

                    b.Property<string>("AccentColor")
                        .HasColumnType("text")
                        .HasColumnName("accent_color");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<string>("DefaultAttendanceMode")
                        .HasColumnType("text")
                        .HasColumnName("default_attendance_mode");

                    b.Property<string>("DefaultGradingMode")
                        .HasColumnType("text")
                        .HasColumnName("default_grading_mode");

                    b.Property<string>("LandingPageJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("landing_page_json");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("text")
                        .HasColumnName("primary_color");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_settings");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_settings_tenant_id");

                    b.ToTable("tenant_settings", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.TenantUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_user_roles");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_tenant_user_roles_branch_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_tenant_user_roles_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_user_roles_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_tenant_user_roles_tenant_id_user_id");

                    b.HasIndex("TenantId", "UserId", "RoleId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_user_roles_tenant_id_user_id_role_id_branch_id");

                    b.ToTable("tenant_user_roles", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ClassNovaApi.Models.AcademicYear", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_years_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.AuditLog", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_tenants_tenant_id");

                    b.HasOne("ClassNovaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Batch", b =>
                {
                    b.HasOne("ClassNovaApi.Models.AcademicYear", "AcademicYear")
                        .WithMany("Batches")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_academic_years_academic_year_id");

                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_batches_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Class", "Class")
                        .WithMany("Batches")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_batches_classes_class_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_tenants_tenant_id");

                    b.Navigation("AcademicYear");

                    b.Navigation("Branch");

                    b.Navigation("Class");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.BatchSubjectTeacher", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batch_subject_teachers_batches_batch_id");

                    b.HasOne("ClassNovaApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batch_subject_teachers_subjects_subject_id");

                    b.HasOne("ClassNovaApi.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batch_subject_teachers_teachers_teacher_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batch_subject_teachers_tenants_tenant_id");

                    b.Navigation("Batch");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Branch", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany("Branches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Class", b =>
                {
                    b.HasOne("ClassNovaApi.Models.AcademicYear", "AcademicYear")
                        .WithMany("Classes")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_academic_years_academic_year_id");

                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classes_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_tenants_tenant_id");

                    b.Navigation("AcademicYear");

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.ClassSchedule", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_schedules_batches_batch_id");

                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_class_schedules_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_schedules_subjects_subject_id");

                    b.HasOne("ClassNovaApi.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_schedules_teachers_teacher_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_schedules_tenants_tenant_id");

                    b.Navigation("Batch");

                    b.Navigation("Branch");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Exam", b =>
                {
                    b.HasOne("ClassNovaApi.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exams_academic_years_academic_year_id");

                    b.HasOne("ClassNovaApi.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exams_batches_batch_id");

                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exams_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exams_tenants_tenant_id");

                    b.Navigation("AcademicYear");

                    b.Navigation("Batch");

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.ExamSubject", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Exam", "Exam")
                        .WithMany("ExamSubjects")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_subjects_exams_exam_id");

                    b.HasOne("ClassNovaApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_subjects_subjects_subject_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_subjects_tenants_tenant_id");

                    b.Navigation("Exam");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.FeePlan", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fee_plans_batches_batch_id");

                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fee_plans_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fee_plans_tenants_tenant_id");

                    b.Navigation("Batch");

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Mark", b =>
                {
                    b.HasOne("ClassNovaApi.Models.ExamSubject", "ExamSubject")
                        .WithMany("Marks")
                        .HasForeignKey("ExamSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marks_exam_subjects_exam_subject_id");

                    b.HasOne("ClassNovaApi.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marks_students_student_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marks_tenants_tenant_id");

                    b.Navigation("ExamSubject");

                    b.Navigation("Student");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.PasswordResetOtp", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_otps_tenants_tenant_id");

                    b.HasOne("ClassNovaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_otps_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Payment", b =>
                {
                    b.HasOne("ClassNovaApi.Models.FeePlan", "FeePlan")
                        .WithMany()
                        .HasForeignKey("FeePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_fee_plans_fee_plan_id");

                    b.HasOne("ClassNovaApi.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_students_student_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_tenants_tenant_id");

                    b.Navigation("FeePlan");

                    b.Navigation("Student");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.PendingRegistration", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pending_registrations_roles_role_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pending_registrations_tenants_tenant_id");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Student", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_students_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_tenants_tenant_id");

                    b.HasOne("ClassNovaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_students_users_user_id");

                    b.Navigation("Branch");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassNovaApi.Models.StudentEnrollment", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_enrollments_batches_batch_id");

                    b.HasOne("ClassNovaApi.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_enrollments_classes_class_id");

                    b.HasOne("ClassNovaApi.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_enrollments_students_student_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_enrollments_tenants_tenant_id");

                    b.Navigation("Batch");

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Subject", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Teacher", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teachers_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_tenants_tenant_id");

                    b.HasOne("ClassNovaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teachers_users_user_id");

                    b.Navigation("Branch");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassNovaApi.Models.TenantFeature", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany("Features")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_features_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.TenantSettings", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithOne("Settings")
                        .HasForeignKey("ClassNovaApi.Models.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_settings_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ClassNovaApi.Models.TenantUserRole", b =>
                {
                    b.HasOne("ClassNovaApi.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tenant_user_roles_branches_branch_id");

                    b.HasOne("ClassNovaApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_user_roles_roles_role_id");

                    b.HasOne("ClassNovaApi.Models.Tenant", "Tenant")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_user_roles_tenants_tenant_id");

                    b.HasOne("ClassNovaApi.Models.User", "User")
                        .WithMany("TenantUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_user_roles_users_user_id");

                    b.Navigation("Branch");

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassNovaApi.Models.AcademicYear", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Class", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Exam", b =>
                {
                    b.Navigation("ExamSubjects");
                });

            modelBuilder.Entity("ClassNovaApi.Models.ExamSubject", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("ClassNovaApi.Models.Tenant", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Features");

                    b.Navigation("Settings");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ClassNovaApi.Models.User", b =>
                {
                    b.Navigation("TenantUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
